# Generated by Django 2.2.4 on 2022-06-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favBooks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
